Voluntary exits
gobitfly/eth2-beaconchain-explorer pull request #1235
Opened 2022-02-10 14:15 UTC by RainerBitfly

@RainerBitfly: Added Paging #470 https://github.com/gobitfly/eth2-beaconchain-explorer/issues/470

2022-02-10 17:13 UTC, RainerBitfly commented
@JustinDrake: Hi, you can find the new view in the dropdown menu (Vol. Exits). Hope it is what you want :) (@RainerBitfly)
![grafik](https://user-images.githubusercontent.com/96172444/153459939-23df522e-0b15-4c74-b0e5-2dc693b11501.png)

2022-02-12 21:14 UTC, JustinDrake commented
Oh yes, this filter view looks great!

As a side note, the current filtering may have a bug. When you filter by "Active", and sort by "Last attestation" you'll find a validator with state "Slashed".

<img width="1052" alt="Screenshot 2022-02-12 at 21 10 22" src="https://user-images.githubusercontent.com/731743/153728567-5e440a90-13f8-4ae3-a0a8-ca09ab79ad95.png">

2022-02-14 08:44 UTC, qu0b approved these changes

2022-02-14 09:49 UTC, qu0b requested changes

2023-02-15 21:00 UTC, closed without merging