Adds support for merged ethereum
gobitfly/eth2-beaconchain-explorer pull request #1241
Opened 2022-02-16 15:36 UTC by parithosh

- Relies on a lighthouse node
- Beaconcha.in will then be able to process the merged beacon chain data
- The slot page will also show the execution payload information

2022-03-11 21:01 UTC, true0131 approved these changes

2022-03-12 06:50 UTC, asaneh requested changes
#eth2_config.yaml @true0131

2022-03-12 07:17 UTC, true0131 approved these changes
Thank you

2022-03-12 08:23 UTC, parithosh commented
Some users noticed that the pending deposits  information isn't updating on this fork(Deployed on kiln tesnet). 

For ensuring the PR is still working, i'd suggest syncing the explorer against the kiln testnet or merge-devnet-5

2022-06-24 10:19 UTC, merged