(BIDS-1646) show validator history up to his exit
gobitfly/eth2-beaconchain-explorer pull request #1883
Opened 2023-03-01 14:35 UTC by MauserBitfly

2023-03-01 16:09 UTC, recy21 approved these changes

2023-03-02 08:04 UTC, D13ce requested changes

2023-03-02 08:04 UTC, D13ce commented on handlers/validator.go
> +	}
This does not meet the requirements specified. According to the [BIDS](https://bitfly1.atlassian.net/browse/BIDS-1646) description, the last entry for an exited validator should be the balance change to 0 ETH.

Let's take your example validator: https://zhejiang.beaconcha.in/validator/62092#deposits

The last entry shown with your changes is their attestation and withdrawal in epoch 3104.

The full withdrawal is not shown though and the problem is that this does not happen during the exit epoch. It happens several epochs after that. The validator in question for example can be fully withdrawn only AFTER epoch 3361 (depending on the witdhdrawal cycle).

So you need to check whether the validator has already been withdrawn completely and if so, add the according entry to the table.

2023-03-02 09:04 UTC, MauserBitfly commented on templates/validator/tables.html
> +        <tbody></tbody>
The table body will be filled by the DataTable library once the data is loaded. 
Yes I tested it and the lib also adds the tbody if its missing, but I think it's nicer to already have it there. And it's also the same for all the other tables in the tables.html that use the DataTable lib.

2023-03-06 08:15 UTC, D13ce commented on handlers/validator.go
> +	}
This has been discussed in the according BIDS and @Buttaa approved that the full withdrawal does not need to be shown in the validator history.

2023-03-06 08:15 UTC, D13ce approved these changes
lgtm

2023-03-06 08:47 UTC, merged