(BIDS-1458) ENS backend
gobitfly/eth2-beaconchain-explorer pull request #1948
Opened 2023-03-15 08:09 UTC by MauserBitfly

2023-03-15 09:33 UTC, recy21 approved these changes

2023-03-17 11:09 UTC, D13ce requested changes
I am afraid we will not be able to follow this approach. I will link my comment explaining why as soon as I have submitted this review (i.e. in the next few seconds)

Furthermore, I have observed the following behavior after starting a local instance of this:

<http://localhost:8081/api/v1/ens/lookup/allice.eth>
```
{"status":"OK","data":{"address":"0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37","domain":"allice.eth"}}
```

<http://localhost:8081/api/v1/ens/lookup/0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37>
```
{"status":"OK","data":{"address":"0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37","domain":"pikyoe.eth"}}
```

Both times the same address is used but a different domain is returned => More than one domain can be registered for the same address. In my opinion, returning only one of them is a bug.

2023-03-17 11:09 UTC, D13ce commented on handlers/ens.go
> +		if address, err := cache.TieredCache.GetStringWithLocalTimeout(cacheKey, time.Hour); err != nil || len(address) == 0 {
As discussed with @peterbitfly, caching introduces inaccuracy as ENS names can change every block.
Removing caching with the implementation here would potentially mean a lot of traffic for our node.

I am afraid we cannot implement this whole feature the way you did. @peterbitfly suggested to index events on the according ENS contract in bigtable to always be up2date and to reduce the load on our nodes.

2023-03-17 15:28 UTC, MauserBitfly commented on handlers/ens.go
> +	return data, returnError //We always want to return the data if it was a valid address/domain even if there was an error getting data from the node. A valid address might be enough for the caller.
> I am afraid we will not be able to follow this approach: [#1948 (comment)](https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1948#discussion_r1140096934)
> 
> Furthermore, I have observed the following behavior after starting a local instance of this:
> 
> http://localhost:8081/api/v1/ens/lookup/allice.eth
> 
> ```
> {"status":"OK","data":{"address":"0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37","domain":"allice.eth"}}
> ```
> 
> http://localhost:8081/api/v1/ens/lookup/0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37
> 
> ```
> {"status":"OK","data":{"address":"0x20a5bD183b420eBBD1BdA4b8818801b9eFa4CA37","domain":"pikyoe.eth"}}
> ```
> 
> Both times the same address is used but a different domain is returned => More than one domain can be registered for the same address. In my opinion, returning only one of them is a bug.

I just tested it now on the ENS page:
You can register multiple ens names with your eth address. And then you can select your 'primary name' and that it exactly the name that we are displaying when you query it with the eth address
![image](https://user-images.githubusercontent.com/125363940/225948674-244c5567-7e9d-4718-bd8e-feb5c73adfb1.png)

![image](https://user-images.githubusercontent.com/125363940/225948754-e2ceaa43-b0c8-4a5e-9d0f-8dfa0797e40b.png)


-> So the behavior is correct as we would show the primary ens name for that eth address.

2023-06-15 11:07 UTC, MauserBitfly commented
replaced by other PR

2023-06-15 11:07 UTC, closed without merging