Bids 1770/explorer configuration administration
gobitfly/eth2-beaconchain-explorer pull request #1959
Opened 2023-03-16 15:02 UTC by MauserBitfly

2023-03-20 09:20 UTC, D13ce requested changes

2023-03-20 09:44 UTC, MauserBitfly commented on tables.sql
> -drop table if exists ad_configurations;
based on a comment by @recy21 (which I cannot find anymore) the drop table was replaced with `if not exists` in the create table statement.

2023-03-20 10:14 UTC, MauserBitfly commented on templates/user/explorer_configuration.html
> +                {{ else if eq $configValue.DataType "bool" }}
@D13ce : There is no restriction on the data types in the backend ... the line you refer to is just from a helper method casting int data types.  The UI for the bool I just thought might come in handy if we need it.

2023-03-20 10:27 UTC, MauserBitfly commented on types/templates.go
> +	Config   ExplorerConfigurationKeyMap
The Idea here is that if we need an additional config for the Frontend we just need to add it to the DefaultExplorerConfiguration without any mapping in the go code.

2023-03-20 10:34 UTC, MauserBitfly commented on types/templates.go
> +		configValue, ok = kyMap[configKey]
fixed

2023-03-20 10:38 UTC, MauserBitfly commented on handlers/index.go
>  	}
I have put it in a separate function, but left it in the index.go file as the logic is specific to the index page. And separated the functions a bit so you can read it better. ;-) 
As I don't think loading the config is vital I didn't log the error messages.

2023-03-20 10:39 UTC, MauserBitfly commented on services/configuration.go
> +	// first we clone de defaults
As "de" to cool for you, I change it "the"

2023-03-20 10:40 UTC, MauserBitfly commented on types/templates.go
> +	return configValue, errors.New("error")
fixed

2023-03-20 10:40 UTC, MauserBitfly commented on types/templates.go
> +func (configMap ExplorerConfigurationMap) GetValue(category ExplorerConfigurationCategory, configKey ExplorerConfigurationKey) (string, error) {
renamed

2023-03-20 10:40 UTC, MauserBitfly commented on templates/user/explorer_configuration.html
> +        <button type="submit" class="btn btn-primary w-100">Save</button>
added a margin - hope it now is usable for you ;-)

2023-03-21 06:43 UTC, D13ce commented on services/configuration.go
> +	// first we clone de defaults
Thank you, youngling.

2023-03-21 06:47 UTC, D13ce commented on templates/user/explorer_configuration.html
> +                {{ else if eq $configValue.DataType "bool" }}
The line link I have chosen wasn't the best, sorry.

My point is the following: We do have a `GetUInt64Value` and a `GetStringValue` but no `GetBooleanValue`. I agree with you, Booleans should be supported. But they should be supported completely and that includes a helper function for Booleans as well. Thoughts?

2023-03-21 06:55 UTC, D13ce commented on templates/user/explorer_configuration.html
> +                {{ else if eq $configValue.DataType "bool" }}
As discussed, adding it to the frontend was the harder part as the input field differs. Adding it to the backend (i.e. implementing the helper function) is super simple and will be done on demand.

2023-03-21 06:57 UTC, D13ce commented on types/templates.go
> +	Config   ExplorerConfigurationKeyMap
I am sorry, that was my bad. I misread the code and thought that the WHOLE explorer configuration is part of `SlotVizPageData`. That is not the case though, only the keymap for `ConfigurationCategorySlotViz` is added (and yes, CURRENTLY this is the whole configuration, but you get what I mean).

2023-03-21 07:49 UTC, D13ce commented on handlers/index.go
> +	}
**Minor:** I would prefer early exits when errors appear like this:
```suggestion
	configuration, err := services.GetExplorerConfigurationsWithDefaults()
	if err != nil {
		return slotVizPageData
	}
	
	visiblFrom, err = configuration.GetUInt64Value(services.ConfigurationCategorySlotViz, services.ConfigurationKeyVisibleFromEpoch)

```

2023-03-21 07:49 UTC, D13ce commented on handlers/index.go
> +func getSlotVizData(currentEpoch uint64) types.SlotVizPageData {
This function does not have any error handling. If errors happen, the slot viz will simply not be shown but there is no information, WHAT went wrong.

This is a delicate topic. For example: We might not want to throw an error log if configuration is missing. But if something else goes wrong? What are your thoughts?

2023-03-21 07:49 UTC, D13ce commented on templates/user/explorer_configuration.html
> +        <button type="submit" class="btn btn-primary w-100">Save</button>
LOVE it!

2023-03-21 07:57 UTC, D13ce reviewed
Left a question regarding error handling. Once that is answered, this PR can be merged.

2023-03-21 09:06 UTC, D13ce approved these changes
lgtm, nice feature!

2023-03-21 09:08 UTC, merged