Bids 1458/ens backend via events
gobitfly/eth2-beaconchain-explorer pull request #1987
Opened 2023-03-23 15:16 UTC by MauserBitfly

This BIDS will probably be replaced by https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2251

Until that one is merged I will leave this open, in case we decide to go another direction

2023-05-22 12:32 UTC, D13ce requested changes
@MauserBitfly, this is quite the big topic. You may have noticed :)

As you brought up in our last brainstorm discussion, there might be a way to simplify everything:
We could try to use the same handling for ENS as done for balances.
Take a look at `func markBalanceUpdate`: It is called for every address that might be subject to a balance change caused by a transaction and "marks" them. Once the block export is done, the node is asked for the up2date balances for every "marked" address.

Why not do the same with ENS? Whenever we find a transaction that does something ENS related, we "mark" the according address and the according name and once the export is done, we ask the node for the latest state.
This would remove a LOT of complexity from our code AND make everything easier for us in the future.

I cannot really estimate the node's workload for that, but I guess it would be one very big call after the complete re-export (that is needed) and then a few minor calls every now and then.

Please ask @peterbitfly for feedback though.

2023-05-23 09:23 UTC, MauserBitfly commented on db/bigtable_eth1.go
> +				continue
I don't want to break the block import, just because we have some issue with the ens event mapping.

2023-05-23 09:25 UTC, MauserBitfly commented on db/bigtable_eth1.go
> +		}
It means we didn't find a registration.

2023-05-25 13:17 UTC, MauserBitfly commented on handlers/ens.go
> +func GetEnsDomain(search string) (*types.EnsDomainResponse, error) {
Its possible that this function will be used also on other places with the FE integration of ENS.

2023-05-25 13:17 UTC, MauserBitfly commented on utils/ens.go
> +	return strings.HasSuffix(text, ".eth") && len(text) > 4
For now we only support .eth as the other domains use different methods of registration and need to be implemented on a 1 by 1 basis

2023-06-15 11:08 UTC, MauserBitfly commented
replaced by other PR

2023-06-15 11:08 UTC, closed without merging