(BIDS-2529) Add block column to tables on address page
gobitfly/eth2-beaconchain-explorer pull request #2619
Opened 2023-10-18 13:39 UTC by D13ce

This PR adds a block column to the tables on the address page, namely to
- Internal Txs
- Blob Txs (for Dencun)
- Erc20 Txs
- Erc721 Txs
- Erc1155 Txs

2023-10-30 08:44 UTC, LuccaBitfly requested changes
Everything seems to look fine, but

2023-10-30 08:44 UTC, LuccaBitfly commented on handlers/eth1Account.go
Opening an address page on your branch, e.g. `/address/0x8be1a5737817d3c8bf65039a8d374f920819563a` on **Holesky**, results in some huge error for me, which does not happen on the master branch.

2023-10-31 08:11 UTC, D13ce commented on handlers/eth1Account.go
What errors are you seeing? Does the page load?

2023-10-31 08:29 UTC, LuccaBitfly approved these changes
lgtm, pls don't hurt me

2023-10-31 08:37 UTC, D13ce commented on handlers/eth1Account.go
As discussed, the error you were talking about was a warning and did not come from my PR.

2023-11-02 07:38 UTC, merged