(BIDS-2981) fix activation estimation for eip-7514
gobitfly/eth2-beaconchain-explorer pull request #2828
Opened 2024-01-30 15:58 UTC by guybrush

2024-01-30 23:40 UTC, Elenore23 approved these changes

2024-01-31 06:10 UTC, D13ce requested changes
The build for this PR fails. You have added a new function `getValidatorActivationChurnLimit` that is not used anywhere. Removing it would solve the build error but it would also render the whole PR almost meaningless as it is the only location where the new config value `MaxPerEpochActivationChurnLimit` is used.

2024-01-31 06:10 UTC, D13ce commented on services/stats.go
>  // GetValidatorChurnLimit returns the rate at which validators can enter or leave the system
This tool tip contains the wrong function name (`GetValidatorChurnLimit`).
Also, is it correct? Based on the function name I would assume that this is only about the enter rate and not about the leave rate.

2024-02-05 09:23 UTC, D13ce approved these changes
utACK

2024-02-05 09:46 UTC, merged